package com.gram.color_android.network.set

enum class FeedSet {
    GET_FEED_SUCCESS,
    GET_FEED_FAIL,
    DELETE_SUCCESS,
    DELETE_FAIL,
    GET_COMMENT_SUCCESS,
    GET_COMMENT_FAIL,
    WRITE_SUCCESS,
    WRITE_FAIL,
    REPORT_SUCCESS,
    REPORT_FAIL,
    LIKE_SUCCESS,
    LIKE_FAIL,
    GET_MORE_SUCCESS,
    GET_MORE_FAIL,
    DELETE_COM_SUCCESS,
    DELETE_COM_FAIL
}